# Travis Config File
# http://docs.travis-ci.com/user/languages/ruby/
# http://docs.travis-ci.com/user/using-postgresql/

language: ruby

rvm:
  - 2.5.8

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - RAILS_ENV=test bundle exec rake test

# https://stackoverflow.com/a/55994304/1093087
services:
    - postgresql

addons:
    postgresql: '9.6'
